name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-mysql:
    name: Build & Push MySQL Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build MySQL Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/custom-mysql:latest ./mysql-custom

      - name: Push MySQL Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/custom-mysql:latest

  build-app:
    name: Build & Push PHP POS App Image
    runs-on: ubuntu-latest
    needs: build-mysql

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build App Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/php-pos-app:latest ./app

      - name: Push App Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/php-pos-app:latest
